### ISSUE TITLE
Can I specify more than one stationboard?

### ISSUE THREAD

**Issue by Rudd-O** [neuhausf/swiss-public-transport-mod#3]
I looked into the code for this https://github.com/home-assistant-ecosystem/python-opendata-transport/blob/master/opendata_transport/__init__.py and it looks like the opendata stationboard object (used by this project) only accepts a string (possibly a number).

The config seems to suggest that one can add more than one stationboard.  I doubt that will work, from a cursory reading of the code.

Can this be clarified in the documentation please?

**Comment by neuhausf** [comment]
The class [OpendataTransportStationboard](https://github.com/home-assistant-ecosystem/python-opendata-transport/blob/master/opendata_transport/__init__.py#L30) does indeed accept only one station. If you want to add more than one stationboard, just add multiple sensors:
```
  - platform: swiss_public_transport_mod
    name: Schüpfen
    limit: 4
    stationboard:
    - Schüpfen
  - platform: swiss_public_transport_mod
    name: Langenthal
    limit: 4
    stationboard:
    - Langenthal
```
In the lovelace dashboard, you can also add multiple cards:
```
type: custom:swiss-stationboard
name: Abfahrt
hide_title: true
platform_name: Gl.
entity:
  - sensor.schupfen

type: custom:swiss-stationboard
name: Abfahrt
hide_title: true
platform_name: Gl.
entity:
  - sensor.langenthal
```
... which leads to:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/7963239/218304403-9226be97-0d81-4b01-804e-8b8aae14ecaa.png">

**Comment by neuhausf** [comment]
If you add multiple stations into the **same sensor**, then they will be aggregated. The lovelace ui will display them together:
```
  - platform: swiss_public_transport_mod
    name: Bern
    limit: 4
    stationboard:
    - Bern
    - Bern, Hirschengraben
```
<img width="259" alt="image" src="https://user-images.githubusercontent.com/7963239/218305123-91276d02-224c-4641-8e25-6df7869907dd.png">

This behaviour is meant for stations which are almost in the same location, but have different names. i.e. "Bern" and "Bern, Hirschengraben".
